### ISSUE TITLE
android 32 not support please new update 

### ISSUE THREAD

**Issue by ShibaTech001** [ArunYogi/cordova-plugin-upi#15]
java.lang.IllegalArgumentException: com.testby.shiba: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at com.cordova.upi.UPIPlugin.acceptPayment(UPIPlugin.java:150)
        at com.cordova.upi.UPIPlugin.execute(UPIPlugin.java:85)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:146)
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:339)
        at android.os.Looper.loopOnce(Looper.java:186)
        at android.os.Looper.loop(Looper.java:334)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by the-deadshot** [comment]
@ShibaTech001 This issue is fixed. I have created a pull request. If you are still facing this issue and want to fix it quickly you can use my repo. 
`yarn add https://github.com/the-deadshot/cordova-plugin-upi`

**Comment by amandylabs** [comment]
Anyone wants to use updated version of UPI payment with all new banks and android API 30+ use below version Cordova plugin.

cordova plugin add cordova-plugin-new-upi-payment
https://github.com/amandylabs/cordova-plugin-new-upi-payment
